sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'

jobs:
  fast_finish: true

  include:
  - python: '3.7'
    dist: xenial
    sudo: required

before_install:
  - uname -a
  - lsb_release -a
  - virtualenv --version
install:
  - pip install -U --pre tox
before_script:
  - tox --version
script:
  - tox -e py
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    on_success: never
    on_failure: always
