conditions: v1

sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

stages:
- test
- name: nightly
  if: type IN (api, cron)

jobs:
  fast_finish: true

  include:
  - python: '3.7'
    dist: xenial
    sudo: required

  - stage: nightly
    name: Test against unstable/dev build of Python
    python: '3.7-dev'

  - stage: nightly
    name: Test against unstable/master build of tox under Python 3.6
    python: '3.6'
    env:
      TOXENV: tox-master

env:
  TOXENV: py
before_install:
  - uname -a
  - lsb_release -a
  - virtualenv --version
install:
  - pip install -U --pre tox
before_script:
  - tox --version
script:
  - tox
after_failure:
  - cat .tox/log/* .tox/*/log/*

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    on_success: never
    on_failure: always
